*Credits: materials from this notebook belong to YSDA [Practical DL](https://github.com/yandexdataschool/Practical_DL) course. Special thanks for making them available online.*

# Lab assignment №1, part 1

This lab assignment consists of several parts. You are supposed to make some transformations, train some models, estimate the quality of the models and explain your results.

Several comments:
* Don't hesitate to ask questions, it's a good practice.
* No private/public sharing, please. The copied assignments will be graded with 0 points.
* Blocks of this lab will be graded separately.

## 1. Matrix differentiation

Since it easy to google every task please please please try to undestand what's going on. The "just answer" thing will be not counted, make sure to present derivation of your solution. It is absolutely OK if you found an answer on web then just exercise in $\LaTeX$ copying it into here.

Useful links: 
[1](http://www.machinelearning.ru/wiki/images/2/2a/Matrix-Gauss.pdf)
[2](http://www.atmos.washington.edu/~dennis/MatrixCalculus.pdf)

## ex. 1

$$  
y = x^Tx,  \quad x \in \mathbb{R}^N 
$$

$$
\frac{dy}{dx} = 
$$ 

## Note

Главные использованные источники при решении задач здесь и далее:

1. [Матричное дифференцирование](https://education.yandex.ru/handbook/ml/article/matrichnoe-differencirovanie) (ex. 1)
2. [Matrix Differentiation](https://www.atmos.washington.edu/~dennis/MatrixCalculus.pdf) (ex. 2, ex. 3)
3. [Заметки по матричным вычислениям и нормальному распределению](http://www.machinelearning.ru/wiki/images/2/2a/Matrix-Gauss.pdf) (ex. 4)


## Solution ex. 1

### Что есть $y = x^Tx$

Иная запись $(1)$:

$$
y = \sum_{i=1}^{N} x_i, \tag{1}
$$

Возьмем любой массив/вектор:
$[4, 6, 7, ..., n]$ где $n$ - это последнее значение бесконечного размера вектора/матрицы.
Его решением будет результат скалярного произведения $(2)$.

$$
4^4 + 6^6 + 7^7 + ... + n^n, \tag{2}
$$

In [1]:
"""Import some stuff"""
import numpy as np
import random

In [2]:
def return_scale_mult(array: np.array) -> np.array:
    return np.sum(array ** array)


arr = np.random.rand(random.randint(3,10))
y = return_scale_mult(array=arr)
print(f'''
Input: \n{arr}

scale multip. \n{y}
''')


Input: 
[0.64514199 0.98594097 0.92259443 0.79156694 0.63843611 0.52053747
 0.86079408]

scale multip. 
5.841007666264538



## Производная скалярного произведения.

Для нахождения производной из (1) необходимо:

### Дифференцирование по $x$

Дифференцировать $y$ по каждой компоненте $x_i$ $(3)$:

$$
\frac{d(x^2_i)}{dx_i} = 2x_i, \tag{3}
$$ 

После чего свенуть производную. Т.к. $y$ - сумма квадратов всех $x_i$, то $y$ по $x$ - вектор, который равен $2x_i$, следовательно (4):

$$
\frac{dy}{dx} = 2x, \tag{4}
$$

In [3]:
dy_dx = 2 * arr
print(f'Result: \n{dy_dx}')

Result: 
[1.29028398 1.97188193 1.84518885 1.58313388 1.27687222 1.04107495
 1.72158817]


## ex. 2

$$ y = tr(AB) \quad A,B \in \mathbb{R}^{N \times N}, \tag{5}$$

$$
\frac{dy}{dA} =
$$

## Solution ex. 2

### Постановка задачи
$A$ и $B$ — квадратные матрицы размерности $N×N$, а $tr(⋅)$ обозначает след матрицы. Нужно найти производную функции $y$ по матрице $A$.

### Объяснение следа
Для поиска следа гипотетической матрицы $K$, необходимо просуммировать ее диагональные элементы $(6)$:

$$
tr(K) = \sum_{i=1}^{N} K_{ii}, \tag{6}
$$

Следовательно, для $(5)$ запись будет как $(7)$:

$$
y = tr(AB) = \sum_{i=1}^{N} (AB)_{ii}, \tag{7}
$$

следовательно:

$$
(AB)_{ii} = \sum_{i=1}^{N} A_{ij} B_{ji}.
$$

где:

- $A_{ij}$​ - элемент матрицы $A$, находящийся в $i$-й строке и $j$-м столбце.
- $B_{ji}$ - элемент матрицы $B$, находящийся в $j$-й строке и $i$-м столбце.


### Дифференцирование
Для доказательства дифференциирования матриц $A$ и $B$ размерности $N×N$ на $A$, необходимо вывести его на основе единичного элемента $A_{mn}$, где $m$ и $n$ - индексы единичного элемента $(8)$.  

$$
\frac{\partial y}{\partial A_{mn}} = \frac{\partial}{\partial A_{mn}} \sum_{i=1}^{N} \sum_{j=1}^{N} A_{ij} B_{ji}, \tag{8}
$$

Но в $(8)$ производная будет ненулевой только в случае, когда индексы $i$ и $j$ совпадают с $m$ и $n$ соответственно. Это связано с тем, что производная выражения $A_{ij}$​ по $A_{mn}$​ равна единице, если $i = m$ и $j = n$, и равна нулю в противном случае. Следовательно, останется только один ненулевой член:

$$
\frac{\partial y}{\partial A_{mn}} = B_{mn}.
$$

Однако, если перевести запись в матричный вид, то:

$$
\frac{dy}{dA} = tr(AB) = B^T. \tag{9}
$$

In [4]:
def mat_size(size: int) -> np.array:
    return np.random.rand(size, size), np.random.rand(size, size)

A, B = mat_size(random.randint(1, 4))
dy_dA = B.T

print(f'''
A:\n{A}

B:\n{B}

dy/dA:\n{dy_dA}
''')


A:
[[0.25539077 0.15742136]
 [0.69599578 0.21634555]]

B:
[[0.48767236 0.22148339]
 [0.33895028 0.33803896]]

dy/dA:
[[0.48767236 0.33895028]
 [0.22148339 0.33803896]]



## ex. 3

$$  
y = x^TAc , \quad A\in \mathbb{R}^{N \times N}, x\in \mathbb{R}^{N}, c\in \mathbb{R}^{N} 
$$

$$
\frac{dy}{dx} =
$$

$$
\frac{dy}{dA} =
$$ 

Hint for the latter (one of the ways): use *ex. 2* result and the fact 
$$
tr(ABC) = tr (CAB)
$$

## Solution ex. 3

### Дифференцирование $dy$ по $dx$

Решение поставленной задачи аналогично $(3)$ и $(4)$, за исключением момента, в котором одним из множителей является матрица $A$ размером $N \times N$, из за которой приходится учитывать элементы матрицы, а также незначительно меняется подсчет. Это вносит следующие коррективы $(10)$:

$$
y = \sum_{i=1}^{N} \sum_{j=1}^{N} x_i A_{ij} c_j. \tag{10}
$$

Следовательно:

$$
\frac{\partial y}{\partial x_i} = \sum_{j=1}^{N} A_{ij} c_j.
$$

В итоге: 

$$
\frac{\partial y}{\partial x} = Ac
$$

In [5]:
size = random.randint(3, 6)
A = np.random.rand(size, size)
x = np.random.rand(size)
c = np.random.rand(size)

dy_dx = np.dot(A, c)
print(f'''
A: \n{A}

x: \n{x}

c: \n{c}

dy_dx: \n{dy_dx}
''')


A: 
[[0.65729127 0.56384117 0.12997272]
 [0.51292982 0.23894533 0.53669777]
 [0.6293818  0.25310716 0.65176484]]

x: 
[0.20636985 0.60869604 0.24449667]

c: 
[0.89821006 0.07202195 0.83925326]

dy_dx: 
[0.7400746  0.92835338 1.1305421 ]



### Дифференцирование $dy$ по $dA$

Аналогично результату, выведенному в формуле $(9)$, а также используя подсказку в представленной задаче, меняем исходную запись $y$:

$$
y = tr(x^TAc) = tr(cx^TA),
$$

и дифференциируем $(12)$ ее по примеру $(11)$:

$$
\frac{\partial tr(CAB)}{\partial A} = C^TB, \tag{11}
$$

$$
\frac{\partial y}{\partial A} = cx^T. \tag{12}
$$

In [6]:
dy_dA = np.outer(c, x)
print(f'dy_dA: \n{dy_dA}')

dy_dA: 
[[0.18536348 0.54673691 0.21960937]
 [0.01486316 0.04383947 0.01760913]
 [0.17319657 0.51085014 0.20519463]]


## ex. 4

Classic matrix factorization example. Given matrix $X$ you need to find $A$, $S$ to approximate $X$. This can be done by simple gradient descent iteratively alternating $A$ and $S$ updates.
$$
J = || X - AS ||_F^2  , \quad A\in \mathbb{R}^{N \times R} , \quad S\in \mathbb{R}^{R \times M}
$$
$$
\frac{dJ}{dS} = ? 
$$

You may use one of the following approaches:

#### First approach
Using ex.2 and the fact:
$$
|| X ||_F^2 = tr(XX^T) 
$$ 
it is easy to derive gradients (you can find it in one of the refs). 

## Solution ex. 4 (?)

Для решения был выбран первый подход.

Исходя из подсказки, данной в описании первого подхода, можно провести следующие манипуляции:

$$
J = \| X - AS \|_F^2 = tr((X - AS)(X -AS)^T),
$$

после чего раскрыть ([3], Таблица 1):

$$
J = tr(XX^T - X S^T A^T - AS X^T + AS S^T A^T). \tag{13}
$$

После чего раскроем каждое слагаемое из $(13)$:
1. $XX^T$ - не меняется. 
2. $X(AS)^T = XS^TA^T$, т.к. $(AS)^T = S^TA^T$.
3. $(AS)X^T$ также остается.
4. $(AS)(AS)^T = ASS^TA^T$.

По итогу:

$$
J = tr(XX^T) - tr(XS^TA^T) - tr(ASX^T) + tr(ASS^TA^T). \tag{14}
$$

Пользуясь формулой, полученной в упр. 2, продифференциируем каждое слагаемое:

1. $\frac{\partial tr(XX^T)}{\partial S} = 0$ 
2. $\frac{\partial (-tr(XS^TA^T))}{\partial S} = -A^TX$
3. $\frac{\partial (-tr(ASX^T))}{\partial S} = -A^TX$
4. $\frac{\partial tr(ASS^TA^T)}{\partial S} = 2A^TAS$.

В результате запись выглядит следующим образом:

$$
\frac{\partial J}{\partial S} = -A^T X - A^T X + 2A^T AS = 2A^T (AS - X).
$$

Ее градиент:

$$
\frac{\partial J}{\partial S} = -2A^T(X - AS)
$$

In [7]:
N = random.randint(2, 6)
R = random.randint(1, 8)
M = random.randint(5, 6)

X = np.random.rand(N, M)
A = np.random.rand(N, R)
S = np.random.rand(R, M)

grad_S = -2 * np.dot(A.T, (X - np.dot(A, S)))

print(f'''
X:\n{X}

A:\n{A}

S:\n{S}

Gradient S (dJ/dS):\n{grad_S}
''')


X:
[[0.70120623 0.77332063 0.47932253 0.36194875 0.10909032]
 [0.72280075 0.6164541  0.6259612  0.93065619 0.22898743]
 [0.2042812  0.69614209 0.85735684 0.93925356 0.24032138]
 [0.72764046 0.65336886 0.59934091 0.45780274 0.55264992]]

A:
[[0.39647189 0.09604869 0.81460578]
 [0.41334904 0.58566941 0.6179349 ]
 [0.98459272 0.29563747 0.08140604]
 [0.26390372 0.18425322 0.71724159]]

S:
[[0.81014071 0.78180252 0.03585262 0.96101219 0.32720406]
 [0.45828195 0.61474614 0.18746731 0.44162875 0.19391965]
 [0.00721205 0.32256334 0.88175529 0.1938108  0.62720321]]

Gradient S (dJ/dS):
[[ 0.85561828  0.60820684 -1.07659691  0.35620026  1.1578448 ]
 [ 0.07677227  0.4132286  -0.27937078 -0.04282786  0.70248457]
 [-1.16982759 -0.00286893  0.49305491  0.21399981  1.4585082 ]]



## 2. kNN questions
Here come the questions from the assignment0_01. Please, refer to the assignment0_01 to get the context of the questions.

### Question 1

Notice the structured patterns in the distance matrix, where some rows or columns are visible brighter. (Note that with the default color scheme black indicates low distances while white indicates high distances.)

- What in the data is the cause behind the distinctly bright rows?
- What causes the columns?

*Your Answer:*

Разница в колонках и столбцах при использовании "матрицы расстояний" заключена лишь в том, с какой стороны представлены презентуемые данные. Например, при задаче сравнения обучающих и тестовых данных для обучения алгоритмической модели машинного обучения (в данном случае - K-NN), с помощью нее можно сравнить сходство между признаками. Яркие ячейки в данной матрице будут означать одно из двух:

1. Шум в данных/выброс относительно признаков.
2. Дисбаланс классов.

Рассмотрение представленных данных с точки зрения колонок/столбцов зависит от подгрузки в матрицу определенных наборов в ось $X$ или $Y$.

Однако, [судя по всему](https://boostedml.com/2018/12/solutions-to-stanfords-cs-231n-assignments-1-inline-problems-knn.html), здесь должна была быть картинка, которая отсутствует в [репозитории](https://github.com/girafe-ai/ml-course/tree/23f_basic/homeworks/lab01_ml_pipeline) на момент написания.

UPD:
Изображение генерится в hw01_knn, скорректированный ответ.

1. Полосы по строкам и столбцам могут указывать на выброс, аномалии или шумы.
2. По представленному изображению можно сделать вывод, что танные состоят из паттернов, т.е. в них присутствуют группы с большими различиями. Темные точки - близки, а светлые - далеки.


### Question 2

We can also use other distance metrics such as L1 distance.
For pixel values $p_{ij}^{(k)}$ at location $(i,j)$ of some image $I_k$, 

the mean $\mu$ across all pixels over all images is $$\mu=\frac{1}{nhw}\sum_{k=1}^n\sum_{i=1}^{h}\sum_{j=1}^{w}p_{ij}^{(k)}$$
And the pixel-wise mean $\mu_{ij}$ across all images is 
$$\mu_{ij}=\frac{1}{n}\sum_{k=1}^np_{ij}^{(k)}.$$
The general standard deviation $\sigma$ and pixel-wise standard deviation $\sigma_{ij}$ is defined similarly.

Which of the following preprocessing steps will not change the performance of a Nearest Neighbor classifier that uses L1 distance? Select all that apply.
1. Subtracting the mean $\mu$ ($\tilde{p}_{ij}^{(k)}=p_{ij}^{(k)}-\mu$.)
2. Subtracting the per pixel mean $\mu_{ij}$  ($\tilde{p}_{ij}^{(k)}=p_{ij}^{(k)}-\mu_{ij}$.)
3. Subtracting the mean $\mu$ and dividing by the standard deviation $\sigma$.
4. Subtracting the pixel-wise mean $\mu_{ij}$ and dividing by the pixel-wise standard deviation $\sigma_{ij}$.
5. Rotating the coordinate axes of the data.

*Your Answer:* 1, 2

*Your Explanation:*

1. вычитание одинакового значения из всех элементов векторов расстояние L1 между ними останется неизменным, так как сдвиг на постоянное значение не влияет на разницу модулей.
2. вычитание среднего значения для каждого пикселя не изменит расстояние L1 между векторами, поскольку это эквивалентно применению сдвига на постоянное значение для каждого пикселя по всем изображениям.
3. масштабирование влияет на значение L1 расстояния, так как изменяются относительные различия между пикселями.
4. масштабирование по каждому пикселю также изменяет относительные различия, что повлияет на значение L1 расстояния.
5. поворот данных изменит взаимное расположение точек, что приведет к изменению расстояний между ними.

## Question 3

Which of the following statements about $k$-Nearest Neighbor ($k$-NN) are true in a classification setting, and for all $k$? Select all that apply.
1. The decision boundary (hyperplane between classes in feature space) of the k-NN classifier is linear.
2. The training error of a 1-NN will always be lower than that of 5-NN.
3. The test error of a 1-NN will always be lower than that of a 5-NN.
4. The time needed to classify a test example with the k-NN classifier grows with the size of the training set.
5. None of the above.

*Your Answer:* 2, 4


*Your Explanation:*

1. Решающие границы у k-NN являются нелинейными. Они зависят от расположения точек обучающей выборки, и граница может быть произвольной формы в зависимости от плотности и расположения данных.
2. Если k = 1, ближаий сосед для каждого примера будет сам этот пример. Ошибка нулевая. Если k = 5, соседние примеры могут принадлежать другому классу, что может привести к ошибкам.
3. При 1 есть вероятность оверфиттинга, что, возможно, приведет к более высокой ошибке на тестах при сравнении с 5. При 5 будет лучшее обобщение данных, что снизит ошибку.
4. При большем размере датасета тратится больше времени на расчет расстояния точки до ближайших точек.
